Inserindo o d_mem
SteffanoP/14064-arquitetura-e-organizacao-de-computadores pull request #11
Opened 2023-03-31 18:21 UTC by Joaovcarvalho23

Permissão para adicionar o módulo d_mem na main

2023-03-31 20:05 UTC, SteffanoP requested changes
Opa @Joaovcarvalho23, verifiquei aqui que você implementou os módulos corretamente no _top-level_. Todavia, acredito que você precise revisar sua implementação, quanto a leitura da memória de dados. Dá uma olhada nos comentários por favor.

2023-03-31 20:05 UTC, SteffanoP commented on projetos/2/d_mem.v
> +      end
Eu verifiquei que esse bloco de leitura cria um monte de latches, o que não é bom para um circuito e verifiquei que teria uma implementação melhor para esse bloco, que não envolve a implementação combinacional (com bloco always). Veja na imagem a quantidade de latches só para fazer a leitura.

![image](https://user-images.githubusercontent.com/26782009/229217208-6842ad6d-18ba-4fc1-92ca-ddb51f96c93b.png)

Basicamente ele cria um latch para cada possível entrada (ao todo acho que seriam umas 32 entradas).

Acredito que se você implementar de forma sequencial a condição vai ficar muito mais simples. Uma forma é fazer o _assignment_ abaixo:

```verilog
assign readData = memRead ? memory[address] : 32'bz;
```

O que acontece aqui:

Na sua implementação (implementação combinacional), você **mantém** o estado na saída, mesmo se a flag MemRead mudar para `false`. Quando fazemos o unset dessa flag, é irrelevante guardar o estado anterior.

Porém numa implementação sequencial, você só manterá 2 estados: O dado (quando MemRead está setado), e Alta impedância (quando MemRead não está setado).

Logo, implementar a leitura de forma sequencial é mais vantajosa.

2023-03-31 20:05 UTC, SteffanoP commented on projetos/2/d_mem.v
> +   reg [31:0] memory [0:(2**32 - 1)];		//cria uma memória de 32 bits com 2^32 elementos, onde cada elemento pode ser acessado através de um endereço de 32 bits.
Então @Joaovcarvalho23, o prof. pediu para que os módulos fosse parametrizáveis; dessa forma, acho que seria interessante você parametrizar toda a parte do tamanho de memória de dados.

@Koda-ms fez algo parecido, e acredito que você pode ver a implementação dela para se basear.

2023-03-31 20:13 UTC, SteffanoP commented on projetos/2/mips.v
> +	d_mem mips_d_mem(ula_result, ReadData2, readData, memWrite, memRead);
@Joaovcarvalho23 acabei de lembrar que o professor também pediu para observar a saída atual da memória de dados como um output do top_leve, daí quando você puder, você poderia juntar o `readData` com o `data_mem` (tecnicamente eles deveriam ser a mesma variável).

2023-04-01 01:42 UTC, Joaovcarvalho23 commented on projetos/2/d_mem.v
> +      end
Massa! Adicionei tua alteração e removi a implementação passada. Porém, o assign dentro de um bloco always block é o "procedural assignment".  Ele não é sintetizável e não deve ser usado. Então ficou dessa forma:
 readData = memRead ? memory[address] : 32'bz;

2023-04-01 01:48 UTC, SteffanoP commented on projetos/2/d_mem.v
> +      end
Se você fizer o assignement fora do bloco Always, vai funcionar, tenta aí!

2023-04-01 02:31 UTC, Joaovcarvalho23 commented on projetos/2/d_mem.v
> +   reg [31:0] memory [0:(2**32 - 1)];		//cria uma memória de 32 bits com 2^32 elementos, onde cada elemento pode ser acessado através de um endereço de 32 bits.
Acabei de fazer isso, adicionei um parâmetro chamado MEM_SIZE, com tamanho de 8 bytes.

2023-04-01 02:33 UTC, Joaovcarvalho23 commented on projetos/2/d_mem.v
> +      end
Tinha 2 formas de se implementar isso:
1º - 'assign readData = memRead ? memory[address] : 32'bz;' fora do bloco always, e com variável do tipo wire;
2º - 'readData = memRead ? memory[address] : 32'bz;' dentro do bloco always, e com variável do tipo reg.

2023-04-01 02:36 UTC, Joaovcarvalho23 commented on projetos/2/mips.v
> +	d_mem mips_d_mem(ula_result, ReadData2, readData, memWrite, memRead);
Então no mips.v eu devo alterar, na linha 40 o 'readData' pelo 'data_mem'?

2023-04-01 15:35 UTC, SteffanoP approved these changes
LGTM!

2023-04-01 15:35 UTC, merged